version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test-network
      
  jira:
    image: atlassian/jira-software
    ports:
      - "8080:8080"
    environment:
      JIRA_DATABASE_TYPE: internal
    volumes:
      - ./server.xml:/opt/atlassian/jira/conf/server.xml
      - jira_data:/var/lib/jira/data
      - jira_application_data:/var/atlassian/application-data/jira
    networks:
      - test-network

  confluence:
    image: atlassian/confluence-server
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgres/test
      - ATL_JDBC_USER=admin
      - ATL_DB_TYPE=postgresql
      - ATL_JDBC_PASSWORD=password
    volumes:
      - confluence_data:/var/lib/confluence/data
      - confluence_application_data:/var/atlassian/application-data/confluence
    depends_on:
      - postgres
    ports:
      - "8090:8090"
    networks:
      - test-network

  jenkins:
    image: jenkins/jenkins
    ports:
      - "8081:8080"
    volumes:
      - ./scheduled_script.py:/opt/scheduled_script.py
      - jenkins_data:/var/lib/jenkins/data
      - jenkins_home:/var/jenkins_home
    networks:
      - test-network

networks:
  test-network:
    external: true

volumes:
  postgres_data:
  jira_data:
  jira_application_data:
  confluence_data:
  confluence_application_data:
  jenkins_data:
  jenkins_home: